[build-system]
requires = ["flit_core >=3.11,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "fud"
authors = [
    {name = "Samuel Thomas", email = "sgt43@cornell.edu"}
]
readme = "README.md"
requires-python = ">=3.7"
dynamic = ["version", "description"]
license = "MIT"
dependencies = [
    "pybind11>=2.5.0",
    "appdirs",
    "toml",
    "halo",
    "termcolor",
    "packaging",
    "numpy",
    "simplejson",
    "networkx>=2.6",
    "calyx-ast",
]

[project.optional-dependencies]
remote = ["paramiko", "scp"]
fpga = ["pynq"]

[project.scripts]
fud = "fud.main:main"

[tool.ruff.lint.per-file-ignores]
"main.py" = ["LOG015"]
"__init__.py" = ["TRY002", "LOG015", "RUF012"]
"remote_context.py" = ["LOG015"]
"json_to_dat.py" = ["TRY002", "LOG015"]
"extract.py" = ["TRY002", "LOG015", "BLE001"]
"execution.py" = ["LOG015"]
"xclbin.py" = ["LOG015"]
"utils.py" = ["LOG015"]