[package]
name = "fake"
version.workspace = true
edition.workspace = true

[dependencies]
argh.workspace = true
cranelift-entity = "0.103.0"
serde.workspace = true
figment = { version = "0.10.12", features = ["toml"] }
pathdiff = { version = "0.2.1", features = ["camino"] }
camino = "1.1.6"
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
