[package]
name = "conv-formats"
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
version = "0.1.0"

[dependencies]
cider-serde.workspace = true
serde.workspace = true

thiserror.workspace = true
num-ir = {path = "../num-ir"}
baa.workspace = true
smallvec.workspace = true
struson = { version = "0.7.2", features = ["serde"] }



[dev-dependencies]
proptest = "1.0.0"
num-ir = {path = "../num-ir", features = ["prop-utils"]}
