[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "futil"
author = "FuTIL Authors"
requires-python = ">=3.4"
home-page = "https://github.com/cucapra/futil"

