[package]
name = "data_gen"
version = "0.1.0"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-ir = { version = "0.1.0", path = "../auxin/num-ir", features = ["rand1"] }
thiserror.workspace = true
baa.workspace = true
serde.workspace = true
lazy_static.workspace = true
serde_json.workspace = true
argh.workspace = true
rand = {version = "0.9.2"}
