[package]
name = "auxin"
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-ir = {path = "num-ir"}
conv-formats = {path="formats"}
serde.workspace = true
argh.workspace = true
thiserror.workspace = true
baa.workspace = true
