ver = "0.2.7"

[[tests]]
name = "Relay to FuTIL"
paths = [ "tests/*.relay" ]
cmd = "python3 relay2futil.py < {}"


# TODO(cgyurgyik): Test behavior of the program. For example,

# fud exec --from futil frontends/relay-futil/tests/tensors_add.expect \
# --to dat -s verilog.data frontends/relay-futil/tests/data/tensors_add.dat

