tool.uv.package = false

[project]
name = "systolic-lang"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "calyx-ast",
    "numpy>=2.3.0",
]


[tool.uv.sources]
calyx-ast = { workspace = true }
