// pub mod add_read_wire;
// pub mod control_lookup;
// pub mod fsm;
// pub mod fsm_enable;
// pub mod fsm_ifen;
// pub mod fsm_par;
// pub mod fsm_seq;
// pub mod fsm_while;
// pub mod interfacing;
// pub mod test_pass;
// pub mod toplevel_component;
pub mod lat_insensitive;
// pub mod fsm_if;
pub mod redundant_par;
pub mod remove_if;
pub mod collapse_seq;
pub mod visitor;
