[package]
name = "calyx-frontend"
version = "0.1.1"
edition.workspace = true
description.workspace = true
authors.workspace = true
license-file.workspace = true
keywords.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
readme.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty.workspace = true
lazy_static.workspace = true
linked-hash-map.workspace = true
log.workspace = true
smallvec.workspace = true
pest.workspace = true
pest_derive.workspace = true
pest_consume.workspace = true

calyx-utils = { path = "../calyx-utils", version = "0.1.1" }
