WHITE_SPACE = _{ " " | "\t" | NEWLINE }
dot         = _{ "." }
colon       = _{ ":" }
ident_syms  = _{ "_" | "-" | "'" }
num         = @{ ASCII_DIGIT+ }
group_name  = @{ (ASCII_ALPHA | ASCII_DIGIT | ident_syms)+ }
path        = @{ (ASCII_ALPHA | ASCII_DIGIT | ident_syms | dot | "/")+ }

entry = { WHITE_SPACE* ~ group_name ~ dot ~ group_name ~ colon ~ WHITE_SPACE ~ path ~ WHITE_SPACE ~ num ~ ("-") ~ num ~ (",")* ~ WHITE_SPACE* }

metadata = {
    SOI ~ entry* ~ EOI
}
