[build-system]
requires = ["uv_build>=0.11.17,<0.12"]
build-backend = "uv_build"

[project]
name = "queues"
authors = [{name = "The Rio Authors"}]
classifiers = ["License :: OSI Approved :: MIT License"]
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.4"
urls.Source = "https://github.com/calyxir/calyx"

[tool.uv.build-backend]
module-name = "queues"
module-root = "" # s.t. uv doesn't search for a 'src'
