[package]
name = "num-ir"
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror.workspace = true
smallvec.workspace = true

rand = { version = "0.10", optional = true, features = [] }

# this can probably be feature-reduced, we don't use all of it
baa.workspace = true

[features]
default = ["short-types", "rand1"]
short-types = []
rand1 = ["dep:rand", "baa/rand1"]

[dev-dependencies]
proptest = "1.0.0"
rand = { version = "0.10"}
