/// Analysis of ir programs.
pub mod analysis;
/// Code generation for FuTIL program.
pub mod backend;
/// Errors generated by the compiler.
pub mod errors;
/// Frontend parsing and AST representation.
pub mod frontend;
/// In-memory representation of programs.
pub mod ir;
/// Passes for FuTIL programs.
pub mod passes;
/// Shared utilities.
pub mod utils;
