name: Deployment

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - name: mdbook
        run: mdbook build
      - name: Build source documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: -p calyx --no-deps
      - name: Move source documentation
        run: |
          mv ./target/doc ./book/source
      - name: rsync
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_KNOWN_HOSTS: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
          DEPLOY_SRC: ./book/
          DEPLOY_DEST: sync/calyx-book
          DEPLOY_2_HOST: courses.cit.cornell.edu
          DEPLOY_2_DEST: coursewww/capra.cs.cornell.edu/htdocs/docs/calyx
        run: |
          echo "$DEPLOY_KEY" > pk
          echo "$DEPLOY_KNOWN_HOSTS" > kh
          chmod 600 pk
          rsync --compress --recursive --checksum --itemize-changes --delete \
            -e "ssh -p \"$DEPLOY_PORT\" -i pk -o 'UserKnownHostsFile kh'" \
            $DEPLOY_SRC $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DEST
          ssh -p $DEPLOY_PORT -i pk -o 'UserKnownHostsFile kh' \
            $DEPLOY_USER@$DEPLOY_HOST \
            rsync --compress --recursive --checksum --itemize-changes \
            --delete -e ssh \
            $DEPLOY_DEST/ $DEPLOY_2_HOST:$DEPLOY_2_DEST

  web:
    name: Web Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: web/yarn.lock
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-pack wasm-bindgen-cli
      - run: yarn
        working-directory: ./web
      - run: yarn build
        working-directory: ./web
      - name: rsync
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_KNOWN_HOSTS: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
          DEPLOY_SRC: ./web/dist/
          DEPLOY_DEST: sync/calyx-demo
          DEPLOY_2_HOST: courses.cit.cornell.edu
          DEPLOY_2_DEST: coursewww/capra.cs.cornell.edu/htdocs/calyx-demo
        run: |
          echo "$DEPLOY_KEY" > pk
          echo "$DEPLOY_KNOWN_HOSTS" > kh
          chmod 600 pk
          rsync --compress --recursive --checksum --itemize-changes --delete \
            -e "ssh -p \"$DEPLOY_PORT\" -i pk -o 'UserKnownHostsFile kh'" \
            $DEPLOY_SRC $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DEST
          ssh -p $DEPLOY_PORT -i pk -o 'UserKnownHostsFile kh' \
            $DEPLOY_USER@$DEPLOY_HOST \
            rsync --compress --recursive --checksum --itemize-changes \
            --delete -e ssh \
            $DEPLOY_DEST/ $DEPLOY_2_HOST:$DEPLOY_2_DEST
