name: Playground Deployment

on:
  push:
    branches:
      - master

jobs:
  playground:
    name: Web Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: web/yarn.lock
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.66.0
            override: true
      - name: Install wasm-pack
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-pack
      - name: Install wasm-bindgen-cli
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --version 0.2.80 -f wasm-bindgen-cli
      - run: yarn
        working-directory: ./web
      - run: yarn build
        working-directory: ./web
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: playground
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/dist
