name: Playground Deployment

on:
  push:
    branches:
      - master

jobs:
  playground:
    name: Web Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: web/yarn.lock
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-pack wasm-bindgen-cli
      - run: yarn
        working-directory: ./web
      - run: yarn build
        working-directory: ./web
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: playground
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/dist
