name: Playground Deployment

on:
  push:
    branches:
      - main

jobs:
  playground:
    name: Web Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Rust stable
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            toolchain: stable
      - name: Install wasm-pack and wasm-bindgen-cli
        uses: taiki-e/install-action@wasm-pack
        with:
          tool: wasm-pack

      - name: Install dependencies
        run: npm ci
        working-directory: ./web

      - name: Build website
        run: npm run build
        working-directory: ./web

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: playground
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/dist
