name: Python

on: [push]

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          entryPoint: "fud"
          args: "--check"
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: TrueBrain/actions-flake8@master
        with:
          max_line_length: 88
          path: fud
