name: Python

on: [push]

jobs:
  format:
    name: Python Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Formatting check
        uses: RojerGS/python-black-check@master
        with:
          line-length: 88
          path: 'fud'
      - name: Linting check
        uses: TrueBrain/actions-flake8@master
        with:
          max_line_length: 88
          path: 'fud'
