name: "Mark stale issues and pull requests"

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          operations-per-run: 30
          remove-stale-when-updated: true
          # Pull request configuration
          days-before-stale-pr: 14
          days-before-stale-pr-draft: 180
          days-before-close-pr: 7
          stale-pr-message: "This pull request has been marked as stale due to inactivity."
          close-pr-message: "Closing this pull request due to inactivity."
          stale-pr-label: "S: Stale"
          # Issue configuration: We only operate on issues that are waiting for a response
          days-before-stale-issue: 14
          days-before-close-issue: 14
          only-issue-labels: "S: Awaiting response"
          stale-issue-message: "Please follow-up with this issue and provide more information on how to close it or make progress on it"
          close-issue-message: "Closing this issue due to inactivity."
          stale-issue-label: "S: Stale"