name: "Mark stale issues and pull requests"

on:
  schedule:
    - cron: "0 12 * * *" # Runs every day at noon

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          operations-per-run: 30
          remove-stale-when-updated: true
          # Pull request configuration
          days-before-stale-pr: 14
          days-before-stale-pr-draft: 180
          days-before-close-pr: 7
          stale-pr-message: "This pull request has not seen activity in 14 days and is being marked as stale. If you're continuing work on this, please reply and state how to get this PR in a mergeable state or what issues it is blocked on. If the PR is not ready for review, please mark it as a draft. The PR will be closed in 7 days if there is no further activity."
          close-pr-message: "This stale PR is being closed because it has not seen any activity in 7 days. If you're planning to continue work on it, please reopen it and mention how to make progress on it."
          stale-pr-label: "S: Stale"
          # Issue configuration: We only operate on issues that are waiting for a response
          days-before-stale-issue: 14
          days-before-close-issue: 14
          only-issue-labels: "S: Awaiting response"
          stale-issue-message: "This issue has been marked as stale. Please follow-up with this issue and provide more information on how to close it or make progress on it. The issue will be closed if it does not see any activity in the next 14 days."
          close-issue-message: "There has been no response on this issue in 14 days after requesting it so we are closing it. If this issue is still a problem for you, please reopen it and provide more information."
          stale-issue-label: "S: Stale"
