branches:
  - name: release

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/github'
  - - '@semantic-release/exec'
    - verifyConditionsCmd: "semantic-release-rust verify-conditions"
      prepareCmd: "semantic-release-rust prepare ${nextRelease.version}"
      publishCmd: "semantic-release-rust publish"
  - - '@semantic-release/git'
    - assets: Cargo.toml
